create table "Batch" (
  "id" INTEGER generated by default as identity unique primary key not null,
  "delivery_date" timestamp not null,
  "provider_id" integer not null,
  "created_at" timestamp not null,
  "created_by" integer not null,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Products_Batch" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "batch_id" integer NOT NULL,
  "prod_id" integer NOT NULL,
  "prod_count" integer NOT null check (prod_count > 0),
  "prod_item_cost" decimal(7,2) check (prod_item_cost > 0),
  "production_date" timestamp,
  "expirity_term" smallint check (expirity_term > 0),
  "prod_batch_cost" decimal(7,2) GENERATED ALWAYS AS (prod_count*prod_item_cost) stored check (prod_batch_cost > prod_item_cost),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(50) NOT NULL,
  "gr_id" integer,
  "price" numeric(6,2) check (price > 0),
  "price_valid_from" timestamp,
  "discount" decimal(5,2) DEFAULT 0 check (discount > 0),
  "discount_start" timestamp,
  "discount_end" timestamp check (discount_end > discount_start),
  "producer_id" integer NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Order_Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "ordr_id" integer NOT NULL,
  "prod_id" integer NOT NULL,
  "prod_amount" smallint NOT NULL DEFAULT 1 check (prod_amount > 0),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer,
  "sorting_criteria" SMALLINT default 1,
  "order_date" timestamp NOT NULL,
  "delivery_type" SMALLINT NOT NULL,
  "deliv_address" varchar(255),
  "deliv_date" date check (deliv_date >= created_at),
  "deliv_time_from" time,
  "deliv_time_till" time check (deliv_time_till > deliv_time_from),
  "cost" decimal(7,2) check (cost >= 0),
  "discount_cost" decimal(6,2) check (discount_cost >= 0),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Sex" (
  "id" SERIAL UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(10) NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Comparison" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Comparison_Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "comp_id" integer NOT NULL,
  "prod_id" integer NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "ProductGroup" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Basket" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "user_id" integer,
  "sorting_criteria" SMALLINT default 1,
  "promo_word" varchar(10),
  "discount" decimal(5,2) check (discount >= 0),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Basket_Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "bsk_id" integer NOT NULL,
  "prod_id" integer NOT NULL,
  "prod_amount" smallint NOT NULL DEFAULT 1 check (prod_amount > 0),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Favorite" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "sorting_criteria" SMALLINT  default 1,
  "user_id" integer,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Favorite_Products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "fav_id" integer,
  "prod_id" integer,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT null check (name not like ''),
  "email" varchar(255) NOT null check (email not like ''),
  "password" varchar(64) NOT null check (password not like ''),
  "role_id" SMALLINT NOT NULL,
  "sex_id" SMALLINT,
  "birthdate" date check (EXTRACT(YEAR FROM AGE(birthdate)) > 1900),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Role" (
  "id" SERIAL UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(20) NOT null  check (name not like ''),
  "description" varchar(255),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Permission" (
  "id" SERIAL UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(20) NOT null  check (name not like ''),
  "description" varchar(255),
  "created_at" timestamp NOT NULL,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Role_Permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "role_id" integer NOT NULL,
  "permis_id" integer NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Counterparty" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(255) not null  check (name not like ''),
  "address" varchar(255),
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

CREATE TABLE "Payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "order_id" integer NOT NULL,
  "bank_id" integer NOT NULL,
  "payment_amount" decimal(7,2) NOT null check (payment_amount > 0),
  "payment_date" timestamp NOT NULL,
  "created_at" timestamp NOT null,
  "created_by" integer NOT NULL,
  "updated_at" timestamp,
  "updated_by" integer
);

COMMENT ON TABLE "Batch" IS 'Партия поставки товара';

COMMENT ON COLUMN "Batch"."delivery_date" IS 'Дата поставки товаров';

COMMENT ON COLUMN "Batch"."provider_id" IS 'Ссылка на Поставщика';

COMMENT ON COLUMN "Batch"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Batch"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Batch"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Batch"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Products_Batch" IS 'Перечень товаров в поставке';

COMMENT ON COLUMN "Products_Batch"."batch_id" IS 'Ссылка на партию поставки';

COMMENT ON COLUMN "Products_Batch"."prod_id" IS 'Ссылка на товар';

COMMENT ON COLUMN "Products_Batch"."prod_count" IS 'Количество единиц товара в поставке';

COMMENT ON COLUMN "Products_Batch"."production_date" IS 'Дата производства';

COMMENT ON COLUMN "Products_Batch"."expirity_term" IS 'Срок годности товара, дней';

COMMENT ON COLUMN "Products_Batch"."prod_batch_cost" IS 'Стоимость партии товара';

COMMENT ON COLUMN "Products_Batch"."prod_item_cost" IS 'Стоимость единицы товара в партии'; 

COMMENT ON COLUMN "Products_Batch"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Products_Batch"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Products_Batch"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Products_Batch"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Product" IS 'Товар';

COMMENT ON COLUMN "Product"."name" IS 'Наименование товара';

COMMENT ON COLUMN "Product"."gr_id" IS 'Ссылка на группу товаров';

COMMENT ON COLUMN "Product"."price" IS 'цена единицы товара';

COMMENT ON COLUMN "Product"."price_valid_from" IS 'Время назначения цены';

COMMENT ON COLUMN "Product"."discount" IS 'Скидка на товар';

COMMENT ON COLUMN "Product"."discount_start" IS 'Начало действия скидки';

COMMENT ON COLUMN "Product"."discount_end" IS 'Окончание действия скидки';

COMMENT ON COLUMN "Product"."producer_id" IS 'Ссылка на производителя товара';

COMMENT ON COLUMN "Product"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Product"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Product"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Product"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Order_Products" IS 'Товары, добавленные в Корзину';

COMMENT ON COLUMN "Order_Products"."ordr_id" IS 'Ссылка на Заказ пользователя';

COMMENT ON COLUMN "Order_Products"."prod_id" IS 'Ссылка на товар';

COMMENT ON COLUMN "Order_Products"."prod_amount" IS 'Количество единиц товара';

COMMENT ON COLUMN "Order_Products"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Order_Products"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Order_Products"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Order_Products"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Order" IS 'Заказ товаров';

COMMENT ON COLUMN "Order"."user_id" IS 'Ссылка на покупателя';

COMMENT ON COLUMN "Order"."sorting_criteria" IS 'Критерий сортировки товаров';

COMMENT ON COLUMN "Order"."order_date" IS 'Дата покупки';

COMMENT ON COLUMN "Order"."delivery_type" IS 'Способ доставки (справочник)';

COMMENT ON COLUMN "Order"."deliv_address" IS 'Адрес доставки';

COMMENT ON COLUMN "Order"."deliv_date" IS 'Дата желаемой доставки';

COMMENT ON COLUMN "Order"."deliv_time_from" IS 'Время желаемой доставки (от)';

COMMENT ON COLUMN "Order"."deliv_time_till" IS 'Время желаемой доставки (до)';

COMMENT ON COLUMN "Order"."cost" IS 'Сумма к оплате, руб.';

COMMENT ON COLUMN "Order"."discount_cost" IS 'Размер общей скидки, руб.';

COMMENT ON COLUMN "Order"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Order"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Order"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Order"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Sex" IS 'Роль пользователя';

COMMENT ON COLUMN "Sex"."name" IS 'Наименование пола';

COMMENT ON COLUMN "Sex"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Sex"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Sex"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Sex"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Comparison" IS 'Сравнение товаров';

COMMENT ON COLUMN "Comparison"."user_id" IS 'Ссылка на покупателя';

COMMENT ON COLUMN "Comparison"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Comparison"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Comparison"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Comparison"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Comparison_Products" IS 'Товары, добавленные в Сравнение';

COMMENT ON COLUMN "Comparison_Products"."comp_id" IS 'Ссылка на Сравнение товаров пользователя';

COMMENT ON COLUMN "Comparison_Products"."prod_id" IS 'Ссылка на товар';

COMMENT ON COLUMN "Comparison_Products"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Comparison_Products"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Comparison_Products"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Comparison_Products"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "ProductGroup" IS 'Товарная группа';

COMMENT ON COLUMN "ProductGroup"."name" IS 'Наименование товарной группы';

COMMENT ON COLUMN "ProductGroup"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "ProductGroup"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "ProductGroup"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "ProductGroup"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Basket" IS 'Корзина товаров';

COMMENT ON COLUMN "Basket"."user_id" IS 'Ссылка на покупателя';

COMMENT ON COLUMN "Basket"."sorting_criteria" IS 'Критерий сортировки товаров';

COMMENT ON COLUMN "Basket"."promo_word" IS 'Кодовое слово по промоакции';

COMMENT ON COLUMN "Basket"."discount" IS 'Размер скидки покупателя по программе лояльности';

COMMENT ON COLUMN "Basket"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Basket"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Basket"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Basket"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Basket_Products" IS 'Товары, добавленные в Корзину';

COMMENT ON COLUMN "Basket_Products"."bsk_id" IS 'Ссылка на Корзину пользователя';

COMMENT ON COLUMN "Basket_Products"."prod_id" IS 'Ссылка на товар';

COMMENT ON COLUMN "Basket_Products"."prod_amount" IS 'Количество единиц товара';

COMMENT ON COLUMN "Basket_Products"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Basket_Products"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Basket_Products"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Basket_Products"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Favorite" IS 'Избранные товары';

COMMENT ON COLUMN "Favorite"."sorting_criteria" IS 'Критерий сортировки товаров';

COMMENT ON COLUMN "Favorite"."user_id" IS 'Ссылка на покупателя';

COMMENT ON COLUMN "Favorite"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Favorite"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Favorite"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Favorite"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Favorite_Products" IS 'Товары, добавленные в Избранное';

COMMENT ON COLUMN "Favorite_Products"."fav_id" IS 'Ссылка на категорию Избранное пользователя';

COMMENT ON COLUMN "Favorite_Products"."prod_id" IS 'Ссылка на товар';

COMMENT ON COLUMN "Favorite_Products"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Favorite_Products"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Favorite_Products"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Favorite_Products"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "User" IS 'Пользователь системы';

COMMENT ON COLUMN "User"."name" IS 'Развернутое имя пользователя (ФИО)';

COMMENT ON COLUMN "User"."email" IS 'Логин пользователя (адрес эл.почты)';

COMMENT ON COLUMN "User"."password" IS 'Хэш пароля пользователя';

COMMENT ON COLUMN "User"."role_id" IS 'Роль пользователя';

COMMENT ON COLUMN "User"."sex_id" IS 'Пол пользователя (справочник)';

COMMENT ON COLUMN "User"."birthdate" IS 'Дата рождения пользователя';

COMMENT ON COLUMN "User"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "User"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "User"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "User"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Role" IS 'Роль пользователя';

COMMENT ON COLUMN "Role"."name" IS 'Наименование роли';

COMMENT ON COLUMN "Role"."description" IS 'Описание роли';

COMMENT ON COLUMN "Role"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Role"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Role"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Role"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Permission" IS 'Разрешение пользователя';

COMMENT ON COLUMN "Permission"."name" IS 'Наименование разрешения';

COMMENT ON COLUMN "Permission"."description" IS 'Описание разрешения';

COMMENT ON COLUMN "Permission"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Permission"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Permission"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Permission"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Role_Permissions" IS 'Разрешения для пользователя';

COMMENT ON COLUMN "Role_Permissions"."role_id" IS 'Ссылка на роль пользователя';

COMMENT ON COLUMN "Role_Permissions"."permis_id" IS 'Ссылка на разрешение';

COMMENT ON COLUMN "Role_Permissions"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Role_Permissions"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Role_Permissions"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Role_Permissions"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Counterparty" IS 'Контрагент';

COMMENT ON COLUMN "Counterparty"."name" IS 'Наименование организации';

COMMENT ON COLUMN "Counterparty"."address" IS 'Адрес организации';

COMMENT ON COLUMN "Counterparty"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Counterparty"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Counterparty"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Counterparty"."updated_by" IS 'Пользователь, обновивший запись';

COMMENT ON TABLE "Payment" IS 'Оплата';

COMMENT ON COLUMN "Payment"."order_id" IS 'Ссылка на заказ';

COMMENT ON COLUMN "Payment"."bank_id" IS 'Ссылка на банк';

COMMENT ON COLUMN "Payment"."payment_amount" IS 'Сумма платежа';

COMMENT ON COLUMN "Payment"."payment_date" IS 'Дата и время платежа';

COMMENT ON COLUMN "Payment"."created_at" IS 'Дата создания записи';

COMMENT ON COLUMN "Payment"."created_by" IS 'Пользователь, создавший запись';

COMMENT ON COLUMN "Payment"."updated_at" IS 'Дата обновления записи';

COMMENT ON COLUMN "Payment"."updated_by" IS 'Пользователь, обновивший запись';

ALTER TABLE "Product" ADD CONSTRAINT "fk_Product_gr_id_ProductGroup" FOREIGN KEY ("gr_id") REFERENCES "ProductGroup" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Favorite_Products" ADD CONSTRAINT "fk_Favorite_Products_prod_id_Product" FOREIGN KEY ("prod_id") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Basket_Products" ADD CONSTRAINT "fk_Basket_Products_bsk_id_Basket" FOREIGN KEY ("bsk_id") REFERENCES "Basket" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Basket_Products" ADD CONSTRAINT "fk_Basket_Products_prod_id_Product" FOREIGN KEY ("prod_id") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Favorite_Products" ADD CONSTRAINT "fk_Favorite_Products_fav_id_Favorite" FOREIGN KEY ("fav_id") REFERENCES "Favorite" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Comparison_Products" ADD CONSTRAINT "fk_Comparison_Products_comp_id_Comparison" FOREIGN KEY ("comp_id") REFERENCES "Comparison" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Comparison_Products" ADD CONSTRAINT "fk_Comparison_Products_prod_id_Product" FOREIGN KEY ("prod_id") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Comparison" ADD CONSTRAINT "fk_Comparison_user_id_User" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Basket" ADD CONSTRAINT "fk_Basket_user_id_User" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Favorite" ADD CONSTRAINT "fk_Favorite_user_id_User" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "User" ADD CONSTRAINT "fk_User_role_id_Role" FOREIGN KEY ("role_id") REFERENCES "Role" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "User" ADD CONSTRAINT "fk_User_sex_id_Sex" FOREIGN KEY ("sex_id") REFERENCES "Sex" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Order" ADD CONSTRAINT "fk_Order_user_id_User" FOREIGN KEY ("user_id") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Order_Products" ADD CONSTRAINT "fk_Order_Products_ordr_id_Order" FOREIGN KEY ("ordr_id") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Order_Products" ADD CONSTRAINT "fk_Order_Products_prod_id_Product" FOREIGN KEY ("prod_id") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Products_Batch" ADD CONSTRAINT "fk_ProductBatch_batch_id_Batch" FOREIGN KEY ("batch_id") REFERENCES "Batch" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Product" ADD CONSTRAINT "fk_Product_producer_id_Counterparty" FOREIGN KEY ("producer_id") REFERENCES "Counterparty" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Batch" ADD CONSTRAINT "fk_Batch_provider_id_Counterparty" FOREIGN KEY ("provider_id") REFERENCES "Counterparty" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Products_Batch" ADD CONSTRAINT "fk_ProductBatch_prod_id_Product" FOREIGN KEY ("prod_id") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Payment" ADD CONSTRAINT "fk_Payment_order_id_Order" FOREIGN KEY ("order_id") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Payment" ADD CONSTRAINT "fk_Payment_bank_id_Counterparty" FOREIGN KEY ("bank_id") REFERENCES "Counterparty" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Role_Permissions" ADD CONSTRAINT "fk_Role_Permissions_permis_id_Permission" FOREIGN KEY ("permis_id") REFERENCES "Permission" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;

ALTER TABLE "Role_Permissions" ADD CONSTRAINT "fk_Role_Permissions_role_id_Role" FOREIGN KEY ("role_id") REFERENCES "Role" ("id") ON DELETE CASCADE ON UPDATE SET DEFAULT;
